"""empty message

Revision ID: 787260df970c
Revises: 
Create Date: 2021-04-28 10:44:22.082232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '787260df970c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_time', sa.DateTime(), nullable=False),
    sa.Column('duration_time', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('narrator', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_time', sa.DateTime(), nullable=False),
    sa.Column('duration_time', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('participents', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_time', sa.DateTime(), nullable=False),
    sa.Column('duration_time', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Audiobook')
    op.drop_table('Podcast')
    op.drop_table('Song')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Song',
    sa.Column('ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Name of the song', sa.String(), autoincrement=False, nullable=False),
    sa.Column('Duration in number of seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Uploaded time', postgresql.ARRAY(sa.DATE()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name='Song_pkey')
    )
    op.create_table('Podcast',
    sa.Column('ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Name of the podcast', sa.String(), autoincrement=False, nullable=False),
    sa.Column('Duration in number of seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Uploaded time', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('Host', sa.String(), autoincrement=False, nullable=False),
    sa.Column('Participants', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='Podcast_pkey')
    )
    op.create_table('Audiobook',
    sa.Column('ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Title of the audiobook', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=False),
    sa.Column('Author of the title', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=False),
    sa.Column('Narrator', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=False),
    sa.Column('Duration in number of seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Uploaded time', postgresql.ARRAY(sa.DATE()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name='Audiobook_pkey')
    )
    op.drop_table('song')
    op.drop_table('podcast')
    op.drop_table('audiobook')
    # ### end Alembic commands ###
